#  Service name
spring.application.name=user-service

#  Server port
server.port=8081

#  Consul Configuration
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true

#  H2 Database Configuration (for development)
spring.datasource.url=jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically create tables based on entities
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Console for debugging (accessible in browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#  Health check & management endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


security.jwt.secret-key= =3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=3600000
logging.level.org.springframework.security=TRACE